import localFont from 'next/font/local'
import "./globals.css";
import Header from './components/header'
import Banner from './components/banners'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Swal from 'sweetalert2'
import React, { Suspense } from "react";

const myFont = localFont({ src: './src/Kanit-Regular.ttf' })

const axios = require('axios');
const callApi = async () => {

  const response = await axios.get('https://api.github.com/users/defunkt');
  await console.log(response.data);

};

export const metadata = {
  title: "FFS-Thailand",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  const Swal = require('sweetalert2')
  
  return (
    <html lang="en">
      <head>
        <meta property="og:image" content="https://next-ffs-master.vercel.app/_next/image?url=%2Flogo.jpg&w=64&q=75"/>
        <link rel="icon" href="/" sizes="any" />
      </head>
      <body className={myFont.className}>

        <Header />

        <Banner />



      <main className='pb-16'>
        <Suspense fallback={<div>Loading...</div>}>
        {children}
        </Suspense>
      </main>



        <script
          // you might need to get a newer version
          src="https://kit.fontawesome.com/fbadad80a0.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
